"""
Dhan Sarthi — Safety Models: SafetyAlert, ScamScan, EntityVerification
TDD Section 12.2 — Safety & Security entities
Persists all Rakshak safety checks for audit and SEBI compliance.
"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, Boolean, DateTime, Float, Integer, ForeignKey
from sqlalchemy.orm import relationship
try:
    from sqlalchemy import JSON
except ImportError:
    from sqlalchemy.dialects.sqlite import JSON
from app.core.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class SafetyAlert(Base):
    """
    Investor-facing safety alert generated by Rakshak.
    Categories: Portfolio / Entity / Content / Investment / Regulatory
    """
    __tablename__ = "safety_alerts"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    # Category: Portfolio / Entity / Content / Investment / Regulatory
    category = Column(String, nullable=False)
    # Severity: High / Medium / Low
    severity = Column(String, default="Medium")
    title = Column(String, nullable=False)
    summary = Column(String, nullable=False)
    recommended_action = Column(String, nullable=True)
    # Status: Needs Attention / Resolved / Reviewed
    status = Column(String, default="Needs Attention")
    created_at = Column(DateTime, default=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)

    user = relationship("User", back_populates="safety_alerts")


class ScamScan(Base):
    """
    Record of every scam content scan performed by Rakshak.
    Uses rule-based risk score (NOT ML probability) — score_basis is always 'keyword_rule_engine'.
    """
    __tablename__ = "scam_scans"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=True, index=True)
    # Content type: TEXT / IMAGE / URL
    content_type = Column(String, default="TEXT")
    content_hash = Column(String, nullable=True)          # SHA-256 of content for deduplication
    rule_based_risk_score = Column(Float, nullable=False)
    score_basis = Column(String, default="keyword_rule_engine")  # Always explicit
    # Risk level: Low / Medium / High / Critical
    risk_level = Column(String, nullable=False)
    flagged_indicators = Column(JSON, default=list)       # List of matched keyword strings
    matched_count = Column(Integer, default=0)
    is_scam = Column(Boolean, nullable=False)
    scanned_at = Column(DateTime, default=datetime.utcnow)


class EntityVerification(Base):
    """Record of every SEBI entity registry lookup."""
    __tablename__ = "entity_verifications"

    id = Column(String, primary_key=True, default=_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=True, index=True)
    queried_name = Column(String, nullable=False)
    found = Column(Boolean, nullable=False)
    entity_name = Column(String, nullable=True)
    reg_no = Column(String, nullable=True)
    category = Column(String, nullable=True)
    status = Column(String, nullable=False)
    verified_at = Column(DateTime, default=datetime.utcnow)
